# Generated by Django 2.2.9 on 2020-01-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('fr-fr', 'Français')], default='en-us', max_length=10),
        ),
    ]
