# Generated by Django 2.2.9 on 2020-01-23 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(help_text='Beginning of the booking', verbose_name='Booking start date & time')),
                ('end_datetime', models.DateTimeField(help_text='End of usage date and time', verbose_name='Booking end date & time')),
                ('title', models.CharField(help_text='Name of the event/reservation. max 250 chars.', max_length=255, verbose_name='Title')),
                ('owner', models.ForeignKey(help_text='User owning this', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('resource', models.ForeignKey(help_text='Booked resource.', on_delete=django.db.models.deletion.CASCADE, to='resources.Resource', verbose_name='Resource')),
            ],
        ),
    ]
