# Generated by Django 2.2.9 on 2020-01-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_add_related_name_to_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_datetime',
            field=models.DateTimeField(db_index=True, help_text='End of usage date and time', verbose_name='Booking end date & time'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_datetime',
            field=models.DateTimeField(db_index=True, help_text='Beginning of the booking', verbose_name='Booking start date & time'),
        ),
        migrations.AlterIndexTogether(
            name='booking',
            index_together={('start_datetime', 'end_datetime')},
        ),
    ]
