# Generated by Django 2.2.9 on 2020-01-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, help_text='Resource location', max_length=255, null=True, verbose_name='Location')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, help_text='Resource capacity in number of persons.', null=True, verbose_name='Capacity')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('type', models.CharField(help_text='Resource type. eg: desk, room, screen, pen, parking spot', max_length=255, verbose_name='Type')),
            ],
        ),
    ]
