# Generated by Django 2.2.9 on 2020-01-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_index_date_fields_for_better_perfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('scheduled', 'Scheduled')], db_index=True, default='scheduled', max_length=15),
        ),
    ]
